// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgtype       string                 `protobuf:"bytes,1,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	InfoJson      string                 `protobuf:"bytes,4,opt,name=info_json,json=infoJson,proto3" json:"info_json,omitempty"` // JSON string for info map
	GeoUri        string                 `protobuf:"bytes,5,opt,name=geo_uri,json=geoUri,proto3" json:"geo_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetMsgtype() string {
	if x != nil {
		return x.Msgtype
	}
	return ""
}

func (x *MessageContent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MessageContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageContent) GetInfoJson() string {
	if x != nil {
		return x.InfoJson
	}
	return ""
}

func (x *MessageContent) GetGeoUri() string {
	if x != nil {
		return x.GeoUri
	}
	return ""
}

type DirectMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Content       *MessageContent        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectMessage) Reset() {
	*x = DirectMessage{}
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMessage) ProtoMessage() {}

func (x *DirectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMessage.ProtoReflect.Descriptor instead.
func (*DirectMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *DirectMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DirectMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DirectMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DirectMessage) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DirectMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendDirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Content       *MessageContent        `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectRequest) Reset() {
	*x = SendDirectRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectRequest) ProtoMessage() {}

func (x *SendDirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectRequest.ProtoReflect.Descriptor instead.
func (*SendDirectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendDirectRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendDirectRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendDirectRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendDirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectResponse) Reset() {
	*x = SendDirectResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectResponse) ProtoMessage() {}

func (x *SendDirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectResponse.ProtoReflect.Descriptor instead.
func (*SendDirectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendDirectResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendDirectResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetDirectHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Peer          string                 `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectHistoryRequest) Reset() {
	*x = GetDirectHistoryRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectHistoryRequest) ProtoMessage() {}

func (x *GetDirectHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDirectHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetDirectHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDirectHistoryRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *GetDirectHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDirectHistoryRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

type GetDirectHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*DirectMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	PrevToken     string                 `protobuf:"bytes,2,opt,name=prev_token,json=prevToken,proto3" json:"prev_token,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectHistoryResponse) Reset() {
	*x = GetDirectHistoryResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectHistoryResponse) ProtoMessage() {}

func (x *GetDirectHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetDirectHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetDirectHistoryResponse) GetMessages() []*DirectMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetDirectHistoryResponse) GetPrevToken() string {
	if x != nil {
		return x.PrevToken
	}
	return ""
}

func (x *GetDirectHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Since         string                 `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *SyncRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type SyncResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextToken      string                 `protobuf:"bytes,1,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	DirectMessages []*DirectMessage       `protobuf:"bytes,2,rep,name=direct_messages,json=directMessages,proto3" json:"direct_messages,omitempty"`
	RoomEvents     []*RoomEvent           `protobuf:"bytes,3,rep,name=room_events,json=roomEvents,proto3" json:"room_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *SyncResponse) GetDirectMessages() []*DirectMessage {
	if x != nil {
		return x.DirectMessages
	}
	return nil
}

func (x *SyncResponse) GetRoomEvents() []*RoomEvent {
	if x != nil {
		return x.RoomEvents
	}
	return nil
}

type RoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ContentJson   string                 `protobuf:"bytes,5,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"` // JSON string for content map
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	mi := &file_pkg_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *RoomEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *RoomEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RoomEvent) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *RoomEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReceiveFederatedDirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Content       *MessageContent        `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveFederatedDirectRequest) Reset() {
	*x = ReceiveFederatedDirectRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveFederatedDirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveFederatedDirectRequest) ProtoMessage() {}

func (x *ReceiveFederatedDirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveFederatedDirectRequest.ProtoReflect.Descriptor instead.
func (*ReceiveFederatedDirectRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveFederatedDirectRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ReceiveFederatedDirectRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ReceiveFederatedDirectRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ReceiveFederatedDirectRequest) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReceiveFederatedDirectRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReceiveFederatedDirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReceivedAt    int64                  `protobuf:"varint,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveFederatedDirectResponse) Reset() {
	*x = ReceiveFederatedDirectResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveFederatedDirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveFederatedDirectResponse) ProtoMessage() {}

func (x *ReceiveFederatedDirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveFederatedDirectResponse.ProtoReflect.Descriptor instead.
func (*ReceiveFederatedDirectResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiveFederatedDirectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReceiveFederatedDirectResponse) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

var File_pkg_proto_message_proto protoreflect.FileDescriptor

const file_pkg_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/message.proto\x12\amessage\"\x86\x01\n" +
	"\x0eMessageContent\x12\x18\n" +
	"\amsgtype\x18\x01 \x01(\tR\amsgtype\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tinfo_json\x18\x04 \x01(\tR\binfoJson\x12\x17\n" +
	"\ageo_uri\x18\x05 \x01(\tR\x06geoUri\"\xad\x01\n" +
	"\rDirectMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x121\n" +
	"\acontent\x18\x04 \x01(\v2\x17.message.MessageContentR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"|\n" +
	"\x11SendDirectRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x121\n" +
	"\acontent\x18\x03 \x01(\v2\x17.message.MessageContentR\acontent\"I\n" +
	"\x12SendDirectResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"t\n" +
	"\x17GetDirectHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\"\x88\x01\n" +
	"\x18GetDirectHistoryResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.message.DirectMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"prev_token\x18\x02 \x01(\tR\tprevToken\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"V\n" +
	"\vSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05since\x18\x02 \x01(\tR\x05since\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"\xa3\x01\n" +
	"\fSyncResponse\x12\x1d\n" +
	"\n" +
	"next_token\x18\x01 \x01(\tR\tnextToken\x12?\n" +
	"\x0fdirect_messages\x18\x02 \x03(\v2\x16.message.DirectMessageR\x0edirectMessages\x123\n" +
	"\vroom_events\x18\x03 \x03(\v2\x12.message.RoomEventR\n" +
	"roomEvents\"\xb7\x01\n" +
	"\tRoomEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fcontent_json\x18\x05 \x01(\tR\vcontentJson\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xbd\x01\n" +
	"\x1dReceiveFederatedDirectRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\x121\n" +
	"\acontent\x18\x04 \x01(\v2\x17.message.MessageContentR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"[\n" +
	"\x1eReceiveFederatedDirectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vreceived_at\x18\x02 \x01(\x03R\n" +
	"receivedAt2\xd0\x02\n" +
	"\x0eMessageService\x12E\n" +
	"\n" +
	"SendDirect\x12\x1a.message.SendDirectRequest\x1a\x1b.message.SendDirectResponse\x12W\n" +
	"\x10GetDirectHistory\x12 .message.GetDirectHistoryRequest\x1a!.message.GetDirectHistoryResponse\x123\n" +
	"\x04Sync\x12\x14.message.SyncRequest\x1a\x15.message.SyncResponse\x12i\n" +
	"\x16ReceiveFederatedDirect\x12&.message.ReceiveFederatedDirectRequest\x1a'.message.ReceiveFederatedDirectResponseB0Z.github.com/arcane/arcanelink/pkg/proto/messageb\x06proto3"

var (
	file_pkg_proto_message_proto_rawDescOnce sync.Once
	file_pkg_proto_message_proto_rawDescData []byte
)

func file_pkg_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)))
	})
	return file_pkg_proto_message_proto_rawDescData
}

var file_pkg_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_message_proto_goTypes = []any{
	(*MessageContent)(nil),                 // 0: message.MessageContent
	(*DirectMessage)(nil),                  // 1: message.DirectMessage
	(*SendDirectRequest)(nil),              // 2: message.SendDirectRequest
	(*SendDirectResponse)(nil),             // 3: message.SendDirectResponse
	(*GetDirectHistoryRequest)(nil),        // 4: message.GetDirectHistoryRequest
	(*GetDirectHistoryResponse)(nil),       // 5: message.GetDirectHistoryResponse
	(*SyncRequest)(nil),                    // 6: message.SyncRequest
	(*SyncResponse)(nil),                   // 7: message.SyncResponse
	(*RoomEvent)(nil),                      // 8: message.RoomEvent
	(*ReceiveFederatedDirectRequest)(nil),  // 9: message.ReceiveFederatedDirectRequest
	(*ReceiveFederatedDirectResponse)(nil), // 10: message.ReceiveFederatedDirectResponse
}
var file_pkg_proto_message_proto_depIdxs = []int32{
	0,  // 0: message.DirectMessage.content:type_name -> message.MessageContent
	0,  // 1: message.SendDirectRequest.content:type_name -> message.MessageContent
	1,  // 2: message.GetDirectHistoryResponse.messages:type_name -> message.DirectMessage
	1,  // 3: message.SyncResponse.direct_messages:type_name -> message.DirectMessage
	8,  // 4: message.SyncResponse.room_events:type_name -> message.RoomEvent
	0,  // 5: message.ReceiveFederatedDirectRequest.content:type_name -> message.MessageContent
	2,  // 6: message.MessageService.SendDirect:input_type -> message.SendDirectRequest
	4,  // 7: message.MessageService.GetDirectHistory:input_type -> message.GetDirectHistoryRequest
	6,  // 8: message.MessageService.Sync:input_type -> message.SyncRequest
	9,  // 9: message.MessageService.ReceiveFederatedDirect:input_type -> message.ReceiveFederatedDirectRequest
	3,  // 10: message.MessageService.SendDirect:output_type -> message.SendDirectResponse
	5,  // 11: message.MessageService.GetDirectHistory:output_type -> message.GetDirectHistoryResponse
	7,  // 12: message.MessageService.Sync:output_type -> message.SyncResponse
	10, // 13: message.MessageService.ReceiveFederatedDirect:output_type -> message.ReceiveFederatedDirectResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_message_proto_init() }
func file_pkg_proto_message_proto_init() {
	if File_pkg_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_message_proto = out.File
	file_pkg_proto_message_proto_goTypes = nil
	file_pkg_proto_message_proto_depIdxs = nil
}
