// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/presence.proto

package presence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // online, offline, away, busy
	StatusMsg     string                 `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceRequest) Reset() {
	*x = UpdatePresenceRequest{}
	mi := &file_pkg_proto_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceRequest) ProtoMessage() {}

func (x *UpdatePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePresenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePresenceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePresenceRequest) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type UpdatePresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePresenceResponse) Reset() {
	*x = UpdatePresenceResponse{}
	mi := &file_pkg_proto_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePresenceResponse) ProtoMessage() {}

func (x *UpdatePresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePresenceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePresenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePresenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_pkg_proto_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{2}
}

func (x *GetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Presence      string                 `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"`
	LastActive    int64                  `protobuf:"varint,3,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	StatusMsg     string                 `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_pkg_proto_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{3}
}

func (x *GetPresenceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPresenceResponse) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *GetPresenceResponse) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *GetPresenceResponse) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type GetMultiplePresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiplePresenceRequest) Reset() {
	*x = GetMultiplePresenceRequest{}
	mi := &file_pkg_proto_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiplePresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiplePresenceRequest) ProtoMessage() {}

func (x *GetMultiplePresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiplePresenceRequest.ProtoReflect.Descriptor instead.
func (*GetMultiplePresenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetMultiplePresenceRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PresenceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Presence      string                 `protobuf:"bytes,2,opt,name=presence,proto3" json:"presence,omitempty"`
	LastActive    int64                  `protobuf:"varint,3,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceInfo) Reset() {
	*x = PresenceInfo{}
	mi := &file_pkg_proto_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceInfo) ProtoMessage() {}

func (x *PresenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceInfo.ProtoReflect.Descriptor instead.
func (*PresenceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceInfo) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *PresenceInfo) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

type GetMultiplePresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presences     []*PresenceInfo        `protobuf:"bytes,1,rep,name=presences,proto3" json:"presences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultiplePresenceResponse) Reset() {
	*x = GetMultiplePresenceResponse{}
	mi := &file_pkg_proto_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultiplePresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultiplePresenceResponse) ProtoMessage() {}

func (x *GetMultiplePresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultiplePresenceResponse.ProtoReflect.Descriptor instead.
func (*GetMultiplePresenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{6}
}

func (x *GetMultiplePresenceResponse) GetPresences() []*PresenceInfo {
	if x != nil {
		return x.Presences
	}
	return nil
}

var File_pkg_proto_presence_proto protoreflect.FileDescriptor

const file_pkg_proto_presence_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/presence.proto\x12\bpresence\"g\n" +
	"\x15UpdatePresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\"2\n" +
	"\x16UpdatePresenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12GetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x13GetPresenceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpresence\x18\x02 \x01(\tR\bpresence\x12\x1f\n" +
	"\vlast_active\x18\x03 \x01(\x03R\n" +
	"lastActive\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x04 \x01(\tR\tstatusMsg\"7\n" +
	"\x1aGetMultiplePresenceRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"d\n" +
	"\fPresenceInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpresence\x18\x02 \x01(\tR\bpresence\x12\x1f\n" +
	"\vlast_active\x18\x03 \x01(\x03R\n" +
	"lastActive\"S\n" +
	"\x1bGetMultiplePresenceResponse\x124\n" +
	"\tpresences\x18\x01 \x03(\v2\x16.presence.PresenceInfoR\tpresences2\x96\x02\n" +
	"\x0fPresenceService\x12S\n" +
	"\x0eUpdatePresence\x12\x1f.presence.UpdatePresenceRequest\x1a .presence.UpdatePresenceResponse\x12J\n" +
	"\vGetPresence\x12\x1c.presence.GetPresenceRequest\x1a\x1d.presence.GetPresenceResponse\x12b\n" +
	"\x13GetMultiplePresence\x12$.presence.GetMultiplePresenceRequest\x1a%.presence.GetMultiplePresenceResponseB1Z/github.com/arcane/arcanelink/pkg/proto/presenceb\x06proto3"

var (
	file_pkg_proto_presence_proto_rawDescOnce sync.Once
	file_pkg_proto_presence_proto_rawDescData []byte
)

func file_pkg_proto_presence_proto_rawDescGZIP() []byte {
	file_pkg_proto_presence_proto_rawDescOnce.Do(func() {
		file_pkg_proto_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_presence_proto_rawDesc), len(file_pkg_proto_presence_proto_rawDesc)))
	})
	return file_pkg_proto_presence_proto_rawDescData
}

var file_pkg_proto_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_presence_proto_goTypes = []any{
	(*UpdatePresenceRequest)(nil),       // 0: presence.UpdatePresenceRequest
	(*UpdatePresenceResponse)(nil),      // 1: presence.UpdatePresenceResponse
	(*GetPresenceRequest)(nil),          // 2: presence.GetPresenceRequest
	(*GetPresenceResponse)(nil),         // 3: presence.GetPresenceResponse
	(*GetMultiplePresenceRequest)(nil),  // 4: presence.GetMultiplePresenceRequest
	(*PresenceInfo)(nil),                // 5: presence.PresenceInfo
	(*GetMultiplePresenceResponse)(nil), // 6: presence.GetMultiplePresenceResponse
}
var file_pkg_proto_presence_proto_depIdxs = []int32{
	5, // 0: presence.GetMultiplePresenceResponse.presences:type_name -> presence.PresenceInfo
	0, // 1: presence.PresenceService.UpdatePresence:input_type -> presence.UpdatePresenceRequest
	2, // 2: presence.PresenceService.GetPresence:input_type -> presence.GetPresenceRequest
	4, // 3: presence.PresenceService.GetMultiplePresence:input_type -> presence.GetMultiplePresenceRequest
	1, // 4: presence.PresenceService.UpdatePresence:output_type -> presence.UpdatePresenceResponse
	3, // 5: presence.PresenceService.GetPresence:output_type -> presence.GetPresenceResponse
	6, // 6: presence.PresenceService.GetMultiplePresence:output_type -> presence.GetMultiplePresenceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_presence_proto_init() }
func file_pkg_proto_presence_proto_init() {
	if File_pkg_proto_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_presence_proto_rawDesc), len(file_pkg_proto_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_presence_proto_goTypes,
		DependencyIndexes: file_pkg_proto_presence_proto_depIdxs,
		MessageInfos:      file_pkg_proto_presence_proto_msgTypes,
	}.Build()
	File_pkg_proto_presence_proto = out.File
	file_pkg_proto_presence_proto_goTypes = nil
	file_pkg_proto_presence_proto_depIdxs = nil
}
