// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/federation.proto

package federation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardDirectMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Msgtype       string                 `protobuf:"bytes,4,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	InfoJson      string                 `protobuf:"bytes,7,opt,name=info_json,json=infoJson,proto3" json:"info_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDirectMessageRequest) Reset() {
	*x = ForwardDirectMessageRequest{}
	mi := &file_pkg_proto_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDirectMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDirectMessageRequest) ProtoMessage() {}

func (x *ForwardDirectMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDirectMessageRequest.ProtoReflect.Descriptor instead.
func (*ForwardDirectMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardDirectMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetMsgtype() string {
	if x != nil {
		return x.Msgtype
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetInfoJson() string {
	if x != nil {
		return x.InfoJson
	}
	return ""
}

func (x *ForwardDirectMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ForwardDirectMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardDirectMessageResponse) Reset() {
	*x = ForwardDirectMessageResponse{}
	mi := &file_pkg_proto_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDirectMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDirectMessageResponse) ProtoMessage() {}

func (x *ForwardDirectMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardDirectMessageResponse.ProtoReflect.Descriptor instead.
func (*ForwardDirectMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardDirectMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ForwardRoomEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ContentJson   string                 `protobuf:"bytes,5,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MemberIds     []string               `protobuf:"bytes,7,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRoomEventRequest) Reset() {
	*x = ForwardRoomEventRequest{}
	mi := &file_pkg_proto_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRoomEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRoomEventRequest) ProtoMessage() {}

func (x *ForwardRoomEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRoomEventRequest.ProtoReflect.Descriptor instead.
func (*ForwardRoomEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardRoomEventRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ForwardRoomEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ForwardRoomEventRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ForwardRoomEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ForwardRoomEventRequest) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *ForwardRoomEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ForwardRoomEventRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type ForwardRoomEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeliveredCount int32                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardRoomEventResponse) Reset() {
	*x = ForwardRoomEventResponse{}
	mi := &file_pkg_proto_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRoomEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRoomEventResponse) ProtoMessage() {}

func (x *ForwardRoomEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRoomEventResponse.ProtoReflect.Descriptor instead.
func (*ForwardRoomEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardRoomEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardRoomEventResponse) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

type QueryUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserRequest) Reset() {
	*x = QueryUserRequest{}
	mi := &file_pkg_proto_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserRequest) ProtoMessage() {}

func (x *QueryUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserRequest.ProtoReflect.Descriptor instead.
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{4}
}

func (x *QueryUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QueryUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Presence      string                 `protobuf:"bytes,3,opt,name=presence,proto3" json:"presence,omitempty"`
	LastActive    int64                  `protobuf:"varint,4,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserResponse) Reset() {
	*x = QueryUserResponse{}
	mi := &file_pkg_proto_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserResponse) ProtoMessage() {}

func (x *QueryUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserResponse.ProtoReflect.Descriptor instead.
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_federation_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryUserResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *QueryUserResponse) GetPresence() string {
	if x != nil {
		return x.Presence
	}
	return ""
}

func (x *QueryUserResponse) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

var File_pkg_proto_federation_proto protoreflect.FileDescriptor

const file_pkg_proto_federation_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/federation.proto\x12\n" +
	"federation\"\xe5\x01\n" +
	"\x1bForwardDirectMessageRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\x12\x18\n" +
	"\amsgtype\x18\x04 \x01(\tR\amsgtype\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1b\n" +
	"\tinfo_json\x18\a \x01(\tR\binfoJson\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"8\n" +
	"\x1cForwardDirectMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe4\x01\n" +
	"\x17ForwardRoomEventRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fcontent_json\x18\x05 \x01(\tR\vcontentJson\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"member_ids\x18\a \x03(\tR\tmemberIds\"]\n" +
	"\x18ForwardRoomEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdelivered_count\x18\x02 \x01(\x05R\x0edeliveredCount\"+\n" +
	"\x10QueryUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x81\x01\n" +
	"\x11QueryUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x1a\n" +
	"\bpresence\x18\x03 \x01(\tR\bpresence\x12\x1f\n" +
	"\vlast_active\x18\x04 \x01(\x03R\n" +
	"lastActive2\xa7\x02\n" +
	"\x11FederationService\x12i\n" +
	"\x14ForwardDirectMessage\x12'.federation.ForwardDirectMessageRequest\x1a(.federation.ForwardDirectMessageResponse\x12]\n" +
	"\x10ForwardRoomEvent\x12#.federation.ForwardRoomEventRequest\x1a$.federation.ForwardRoomEventResponse\x12H\n" +
	"\tQueryUser\x12\x1c.federation.QueryUserRequest\x1a\x1d.federation.QueryUserResponseB3Z1github.com/arcane/arcanelink/pkg/proto/federationb\x06proto3"

var (
	file_pkg_proto_federation_proto_rawDescOnce sync.Once
	file_pkg_proto_federation_proto_rawDescData []byte
)

func file_pkg_proto_federation_proto_rawDescGZIP() []byte {
	file_pkg_proto_federation_proto_rawDescOnce.Do(func() {
		file_pkg_proto_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_federation_proto_rawDesc), len(file_pkg_proto_federation_proto_rawDesc)))
	})
	return file_pkg_proto_federation_proto_rawDescData
}

var file_pkg_proto_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_federation_proto_goTypes = []any{
	(*ForwardDirectMessageRequest)(nil),  // 0: federation.ForwardDirectMessageRequest
	(*ForwardDirectMessageResponse)(nil), // 1: federation.ForwardDirectMessageResponse
	(*ForwardRoomEventRequest)(nil),      // 2: federation.ForwardRoomEventRequest
	(*ForwardRoomEventResponse)(nil),     // 3: federation.ForwardRoomEventResponse
	(*QueryUserRequest)(nil),             // 4: federation.QueryUserRequest
	(*QueryUserResponse)(nil),            // 5: federation.QueryUserResponse
}
var file_pkg_proto_federation_proto_depIdxs = []int32{
	0, // 0: federation.FederationService.ForwardDirectMessage:input_type -> federation.ForwardDirectMessageRequest
	2, // 1: federation.FederationService.ForwardRoomEvent:input_type -> federation.ForwardRoomEventRequest
	4, // 2: federation.FederationService.QueryUser:input_type -> federation.QueryUserRequest
	1, // 3: federation.FederationService.ForwardDirectMessage:output_type -> federation.ForwardDirectMessageResponse
	3, // 4: federation.FederationService.ForwardRoomEvent:output_type -> federation.ForwardRoomEventResponse
	5, // 5: federation.FederationService.QueryUser:output_type -> federation.QueryUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_federation_proto_init() }
func file_pkg_proto_federation_proto_init() {
	if File_pkg_proto_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_federation_proto_rawDesc), len(file_pkg_proto_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_federation_proto_goTypes,
		DependencyIndexes: file_pkg_proto_federation_proto_depIdxs,
		MessageInfos:      file_pkg_proto_federation_proto_msgTypes,
	}.Build()
	File_pkg_proto_federation_proto = out.File
	file_pkg_proto_federation_proto_goTypes = nil
	file_pkg_proto_federation_proto_depIdxs = nil
}
