// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/room.proto

package room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Invite        []string               `protobuf:"bytes,4,rep,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateRoomRequest) GetInvite() []string {
	if x != nil {
		return x.Invite
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InviteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Inviter       string                 `protobuf:"bytes,2,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee       string                 `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{6}
}

func (x *InviteUserRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InviteUserRequest) GetInviter() string {
	if x != nil {
		return x.Inviter
	}
	return ""
}

func (x *InviteUserRequest) GetInvitee() string {
	if x != nil {
		return x.Invitee
	}
	return ""
}

type InviteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserResponse) Reset() {
	*x = InviteUserResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserResponse) ProtoMessage() {}

func (x *InviteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserResponse.ProtoReflect.Descriptor instead.
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{7}
}

func (x *InviteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendRoomMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Msgtype       string                 `protobuf:"bytes,3,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	InfoJson      string                 `protobuf:"bytes,6,opt,name=info_json,json=infoJson,proto3" json:"info_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRoomMessageRequest) Reset() {
	*x = SendRoomMessageRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRoomMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRoomMessageRequest) ProtoMessage() {}

func (x *SendRoomMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRoomMessageRequest.ProtoReflect.Descriptor instead.
func (*SendRoomMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{8}
}

func (x *SendRoomMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendRoomMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendRoomMessageRequest) GetMsgtype() string {
	if x != nil {
		return x.Msgtype
	}
	return ""
}

func (x *SendRoomMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendRoomMessageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SendRoomMessageRequest) GetInfoJson() string {
	if x != nil {
		return x.InfoJson
	}
	return ""
}

type SendRoomMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRoomMessageResponse) Reset() {
	*x = SendRoomMessageResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRoomMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRoomMessageResponse) ProtoMessage() {}

func (x *SendRoomMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRoomMessageResponse.ProtoReflect.Descriptor instead.
func (*SendRoomMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{9}
}

func (x *SendRoomMessageResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SendRoomMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetRoomMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersRequest) Reset() {
	*x = GetRoomMembersRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersRequest) ProtoMessage() {}

func (x *GetRoomMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersRequest.ProtoReflect.Descriptor instead.
func (*GetRoomMembersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomMembersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	mi := &file_pkg_proto_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{11}
}

func (x *RoomMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type GetRoomMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*RoomMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomMembersResponse) Reset() {
	*x = GetRoomMembersResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomMembersResponse) ProtoMessage() {}

func (x *GetRoomMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomMembersResponse.ProtoReflect.Descriptor instead.
func (*GetRoomMembersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomMembersResponse) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{13}
}

func (x *GetRoomsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	MemberCount   int32                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	LastActivity  int64                  `protobuf:"varint,5,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_pkg_proto_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{14}
}

func (x *RoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RoomInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *RoomInfo) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{15}
}

func (x *GetRoomsResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetRoomHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomHistoryRequest) Reset() {
	*x = GetRoomHistoryRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomHistoryRequest) ProtoMessage() {}

func (x *GetRoomHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRoomHistoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{16}
}

func (x *GetRoomHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRoomHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRoomHistoryRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

type RoomEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ContentJson   string                 `protobuf:"bytes,5,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	mi := &file_pkg_proto_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{17}
}

func (x *RoomEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RoomEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomEvent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *RoomEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RoomEvent) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *RoomEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetRoomHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RoomEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	PrevToken     string                 `protobuf:"bytes,2,opt,name=prev_token,json=prevToken,proto3" json:"prev_token,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomHistoryResponse) Reset() {
	*x = GetRoomHistoryResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomHistoryResponse) ProtoMessage() {}

func (x *GetRoomHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRoomHistoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoomHistoryResponse) GetEvents() []*RoomEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetRoomHistoryResponse) GetPrevToken() string {
	if x != nil {
		return x.PrevToken
	}
	return ""
}

func (x *GetRoomHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetRoomStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateRequest) Reset() {
	*x = GetRoomStateRequest{}
	mi := &file_pkg_proto_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateRequest) ProtoMessage() {}

func (x *GetRoomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateRequest.ProtoReflect.Descriptor instead.
func (*GetRoomStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{19}
}

func (x *GetRoomStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Creator       string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateResponse) Reset() {
	*x = GetRoomStateResponse{}
	mi := &file_pkg_proto_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateResponse) ProtoMessage() {}

func (x *GetRoomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateResponse.ProtoReflect.Descriptor instead.
func (*GetRoomStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_room_proto_rawDescGZIP(), []int{20}
}

func (x *GetRoomStateResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomStateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoomStateResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetRoomStateResponse) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *GetRoomStateResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetRoomStateResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

var File_pkg_proto_room_proto protoreflect.FileDescriptor

const file_pkg_proto_room_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/room.proto\x12\x04room\"o\n" +
	"\x11CreateRoomRequest\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x16\n" +
	"\x06invite\x18\x04 \x03(\tR\x06invite\"L\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"C\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x10JoinRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tjoined_at\x18\x02 \x01(\x03R\bjoinedAt\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"`\n" +
	"\x11InviteUserRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\ainviter\x18\x02 \x01(\tR\ainviter\x12\x18\n" +
	"\ainvitee\x18\x03 \x01(\tR\ainvitee\".\n" +
	"\x12InviteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x16SendRoomMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x18\n" +
	"\amsgtype\x18\x03 \x01(\tR\amsgtype\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tinfo_json\x18\x06 \x01(\tR\binfoJson\"R\n" +
	"\x17SendRoomMessageResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"0\n" +
	"\x15GetRoomMembersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"B\n" +
	"\n" +
	"RoomMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tjoined_at\x18\x02 \x01(\x03R\bjoinedAt\"D\n" +
	"\x16GetRoomMembersResponse\x12*\n" +
	"\amembers\x18\x01 \x03(\v2\x10.room.RoomMemberR\amembers\"*\n" +
	"\x0fGetRoomsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x95\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x05R\vmemberCount\x12#\n" +
	"\rlast_activity\x18\x05 \x01(\x03R\flastActivity\"8\n" +
	"\x10GetRoomsResponse\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.room.RoomInfoR\x05rooms\"w\n" +
	"\x15GetRoomHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\"\xb7\x01\n" +
	"\tRoomEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fcontent_json\x18\x05 \x01(\tR\vcontentJson\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"{\n" +
	"\x16GetRoomHistoryResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.room.RoomEventR\x06events\x12\x1d\n" +
	"\n" +
	"prev_token\x18\x02 \x01(\tR\tprevToken\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\".\n" +
	"\x13GetRoomStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\xb5\x01\n" +
	"\x14GetRoomStateResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\acreator\x18\x04 \x01(\tR\acreator\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount2\xf4\x04\n" +
	"\vRoomService\x12?\n" +
	"\n" +
	"CreateRoom\x12\x17.room.CreateRoomRequest\x1a\x18.room.CreateRoomResponse\x129\n" +
	"\bJoinRoom\x12\x15.room.JoinRoomRequest\x1a\x16.room.JoinRoomResponse\x12<\n" +
	"\tLeaveRoom\x12\x16.room.LeaveRoomRequest\x1a\x17.room.LeaveRoomResponse\x12?\n" +
	"\n" +
	"InviteUser\x12\x17.room.InviteUserRequest\x1a\x18.room.InviteUserResponse\x12N\n" +
	"\x0fSendRoomMessage\x12\x1c.room.SendRoomMessageRequest\x1a\x1d.room.SendRoomMessageResponse\x12K\n" +
	"\x0eGetRoomMembers\x12\x1b.room.GetRoomMembersRequest\x1a\x1c.room.GetRoomMembersResponse\x129\n" +
	"\bGetRooms\x12\x15.room.GetRoomsRequest\x1a\x16.room.GetRoomsResponse\x12K\n" +
	"\x0eGetRoomHistory\x12\x1b.room.GetRoomHistoryRequest\x1a\x1c.room.GetRoomHistoryResponse\x12E\n" +
	"\fGetRoomState\x12\x19.room.GetRoomStateRequest\x1a\x1a.room.GetRoomStateResponseB-Z+github.com/arcane/arcanelink/pkg/proto/roomb\x06proto3"

var (
	file_pkg_proto_room_proto_rawDescOnce sync.Once
	file_pkg_proto_room_proto_rawDescData []byte
)

func file_pkg_proto_room_proto_rawDescGZIP() []byte {
	file_pkg_proto_room_proto_rawDescOnce.Do(func() {
		file_pkg_proto_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_room_proto_rawDesc), len(file_pkg_proto_room_proto_rawDesc)))
	})
	return file_pkg_proto_room_proto_rawDescData
}

var file_pkg_proto_room_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_proto_room_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),       // 0: room.CreateRoomRequest
	(*CreateRoomResponse)(nil),      // 1: room.CreateRoomResponse
	(*JoinRoomRequest)(nil),         // 2: room.JoinRoomRequest
	(*JoinRoomResponse)(nil),        // 3: room.JoinRoomResponse
	(*LeaveRoomRequest)(nil),        // 4: room.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),       // 5: room.LeaveRoomResponse
	(*InviteUserRequest)(nil),       // 6: room.InviteUserRequest
	(*InviteUserResponse)(nil),      // 7: room.InviteUserResponse
	(*SendRoomMessageRequest)(nil),  // 8: room.SendRoomMessageRequest
	(*SendRoomMessageResponse)(nil), // 9: room.SendRoomMessageResponse
	(*GetRoomMembersRequest)(nil),   // 10: room.GetRoomMembersRequest
	(*RoomMember)(nil),              // 11: room.RoomMember
	(*GetRoomMembersResponse)(nil),  // 12: room.GetRoomMembersResponse
	(*GetRoomsRequest)(nil),         // 13: room.GetRoomsRequest
	(*RoomInfo)(nil),                // 14: room.RoomInfo
	(*GetRoomsResponse)(nil),        // 15: room.GetRoomsResponse
	(*GetRoomHistoryRequest)(nil),   // 16: room.GetRoomHistoryRequest
	(*RoomEvent)(nil),               // 17: room.RoomEvent
	(*GetRoomHistoryResponse)(nil),  // 18: room.GetRoomHistoryResponse
	(*GetRoomStateRequest)(nil),     // 19: room.GetRoomStateRequest
	(*GetRoomStateResponse)(nil),    // 20: room.GetRoomStateResponse
}
var file_pkg_proto_room_proto_depIdxs = []int32{
	11, // 0: room.GetRoomMembersResponse.members:type_name -> room.RoomMember
	14, // 1: room.GetRoomsResponse.rooms:type_name -> room.RoomInfo
	17, // 2: room.GetRoomHistoryResponse.events:type_name -> room.RoomEvent
	0,  // 3: room.RoomService.CreateRoom:input_type -> room.CreateRoomRequest
	2,  // 4: room.RoomService.JoinRoom:input_type -> room.JoinRoomRequest
	4,  // 5: room.RoomService.LeaveRoom:input_type -> room.LeaveRoomRequest
	6,  // 6: room.RoomService.InviteUser:input_type -> room.InviteUserRequest
	8,  // 7: room.RoomService.SendRoomMessage:input_type -> room.SendRoomMessageRequest
	10, // 8: room.RoomService.GetRoomMembers:input_type -> room.GetRoomMembersRequest
	13, // 9: room.RoomService.GetRooms:input_type -> room.GetRoomsRequest
	16, // 10: room.RoomService.GetRoomHistory:input_type -> room.GetRoomHistoryRequest
	19, // 11: room.RoomService.GetRoomState:input_type -> room.GetRoomStateRequest
	1,  // 12: room.RoomService.CreateRoom:output_type -> room.CreateRoomResponse
	3,  // 13: room.RoomService.JoinRoom:output_type -> room.JoinRoomResponse
	5,  // 14: room.RoomService.LeaveRoom:output_type -> room.LeaveRoomResponse
	7,  // 15: room.RoomService.InviteUser:output_type -> room.InviteUserResponse
	9,  // 16: room.RoomService.SendRoomMessage:output_type -> room.SendRoomMessageResponse
	12, // 17: room.RoomService.GetRoomMembers:output_type -> room.GetRoomMembersResponse
	15, // 18: room.RoomService.GetRooms:output_type -> room.GetRoomsResponse
	18, // 19: room.RoomService.GetRoomHistory:output_type -> room.GetRoomHistoryResponse
	20, // 20: room.RoomService.GetRoomState:output_type -> room.GetRoomStateResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_room_proto_init() }
func file_pkg_proto_room_proto_init() {
	if File_pkg_proto_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_room_proto_rawDesc), len(file_pkg_proto_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_room_proto_goTypes,
		DependencyIndexes: file_pkg_proto_room_proto_depIdxs,
		MessageInfos:      file_pkg_proto_room_proto_msgTypes,
	}.Build()
	File_pkg_proto_room_proto = out.File
	file_pkg_proto_room_proto_goTypes = nil
	file_pkg_proto_room_proto_depIdxs = nil
}
